### ISSUE TITLE
Visibility Identifiers

### ISSUE THREAD

**Issue by mozharovsky** [Athlee/VIPCodeGenerator#1]
This generator does not support custom visibility identifiers. 

## Approach 

It is actually more difficult than it looks like. Some members of classes/structs might be declared with the most strict access identifier – `private`, some might be declared less strictly with the `fileprivale` identifier, standard access would be `internal` and customizable up to the `open`.

This generator should be dealing with these requirements and provide an easy and elegant configuration to set those identifiers. 

## Tasks

- [ ] Add configurator for accessibility identifiers
- [ ] Add an easy way to customize the accessibility configurator
- [ ] Update the pod
